# Generated by Django 4.1.2 on 2022-10-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('CodeId', models.AutoField(primary_key=True, serialize=False)),
                ('CodeInput', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('ProblemId', models.AutoField(primary_key=True, serialize=False)),
                ('LectureName', models.CharField(max_length=500)),
                ('ProblemName', models.CharField(max_length=500)),
                ('DeadLine', models.DateField()),
                ('ProblemExplanation', models.TextField()),
                ('Requirements', models.TextField()),
                ('TestCaseId', models.IntegerField()),
                ('RelatedResources', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('TestCaseId', models.AutoField(primary_key=True, serialize=False)),
                ('CaseInput', models.CharField(max_length=500)),
                ('CaseOutput', models.CharField(max_length=500)),
            ],
        ),
    ]
