# Generated by Django 4.1.2 on 2022-10-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code_saved',
            name='code',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='code_submitted',
            name='code',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='code_submitted',
            name='sub_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answerCode',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='deadline',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='problemExplain',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='questionName',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='question',
            name='relatedResource',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='requirements',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='skeletonCode',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='submissionCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testcase',
            name='input',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='testcase',
            name='isHidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testcase',
            name='output',
            field=models.TextField(default=''),
        ),
    ]
