# Generated by Django 4.1.2 on 2022-12-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_rename_problemexplain_question_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='code_submitted',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='code_submitted',
            name='code_submittedId',
            field=models.IntegerField(default=0),
        ),
    ]
