# Generated by Django 4.1.2 on 2022-12-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_code_submitted_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code_submitted',
            name='sub_date',
            field=models.DateTimeField(null=True),
        ),
    ]
