# Generated by Django 4.1.2 on 2022-12-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_alter_code_submitted_sub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='code_saved',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='code_saved',
            name='code_savedId',
            field=models.IntegerField(default=0),
        ),
    ]
